### ISSUE TITLE
Support TYPO3 CMS 9 LTS

### ISSUE THREAD

**Issue by iresults-tma** [digedag/t3sportstats#11]
Vielen Dank für die Updates von cfc_league und cfc_league_fe für TYPO3 CMS 9 LTS.

Ist geplant, dass die Erweiterung t3sportstats auch noch angepasst wird?

**Comment by digedag** [comment]
Na klar. Sollte spätestens im Laufe des Mai fertig werden!

**Comment by digedag** [comment]
Mit Version 1.0.0 gelöst.
