### ISSUE TITLE
Statistiktabellen leer

### ISSUE THREAD

**Issue by stemeda** [digedag/t3sportstats#8]
Hallo,

ich möchte mit diesem Plugin Statistiken bereit stellen. Installation klappt, aber die Datenbanktabellen bleiben leer. Ich habe im Modul "T3Sports" in der Wettbewerbsverwaltung auf den Blitz neben dem Wettbewert geklickt. Laut der [Doku](https://docs.typo3.org/typo3cms/extensions/t3sportstats/ExtStatisticsForT3sports/UsersManual/HowDoesItWork/Index.html) war der wohl dafür gedacht. Ist das noch aktuell oder werden die Statistiken automatisch aktuallisiert?

Typo3 7.6
Alle Erweiterungen sind vom Master aus github

**Comment by digedag** [comment]
Der Button ist immer noch aktuell und das sollte auch in der 7.6 funktionieren... Die Datengrundlage sind die MatchNotes der Spiele, also die Tore, Auswechslungen, Karten usw. Wenn da was gefunden wird, dann sollten sich die Tabellen auch füllen.

**Comment by stemeda** [comment]
Danke für das schnelle Feedback. Ja ich habe MatchNotes angelegt, zumindest für ein paar Spiele zum Testen. Ich habe den Button mehrfach gedrückt. Die Statistiktabellen bleiben leer. Kann ich sonst einen Fehler gemacht haben bzw. das irgendwie debuggen? Die Logs bleiben leer.

**Comment by digedag** [comment]
Es werden nur Spiele ausgewertet, die auf dem Status "beendet" stehen. Wenn du devlog oder mklog installiert hast, dann gibt es dort eine kurze Auswertung.
Wenn du debuggen willst, dann solltest du in [indexStatsByMatches()](https://github.com/digedag/t3sportstats/blob/e4f03011ca6b650b53fb269d57b7989b50f2c06d/srv/class.tx_t3sportstats_srv_Statistics.php#L63) beginnen. :smile:

**Comment by stemeda** [comment]
Ich hab sowohl devlog als auch mklog ausprobiert. In beiden Erweiterungen werden keine Log von t3sportstats angelegt. Ich habe gesehen, das die Methode https://github.com/digedag/t3sportstats/blob/e4f03011ca6b650b53fb269d57b7989b50f2c06d/srv/class.tx_t3sportstats_srv_Statistics.php#L63 Logeinträge anlegen soll.

Ich hab aber mal den Link mit dem Blitz im HTML analysiert. Kann es sein, dass der falsch generiert wird?
```html
<a href="#" class="btn btn-default btn-sm" onclick="return jumpToUrl('/typo3/index.php?route=%2Frecord%2Fcommit&amp;token=TOKEN&amp;redirect=%2Ftypo3%2Findex.php%3FM%3Dweb_CfcLeagueM1%26moduleToken%3DMODULETOKENf3%26id%3D306&amp;amp;&amp;clearCache=1&amp;amp;vC=be1cef70c0&amp;formToken=FORMTOKEN');">
    <span class="t3js-icon icon icon-size-small icon-state-default icon-actions-system-cache-clear" data-identifier="actions-system-cache-clear">
        <span class="icon-markup">
            <img src="/typo3/sysext/core/Resources/Public/Icons/T3Icons/actions/actions-system-cache-clear.svg" width="16" height="16">
        </span>
    </span>
</a>
```
Wenn in den Link aufrufe werden folgende Parameter an die URL `https://sv-neunkirchen-steinborn.de/typo3/index.php` im Query übergeben:
```
route:"/record/commit"
token:"TOKEN"
redirect:"/typo3/index.php?M=web_CfcLeagueM1&moduleToken=MODULETOKEN&id=306"
amp;:""
clearCache:"1"
amp;vC:"be1cef70c0"
formToken:"FORMTOKEN"
```
Ich erhalte einen HTTP 303 Redirect an die gleiche URL mit den Parametern:
```
M:"web_CfcLeagueM1"
moduleToken:"MODULETOKEN"
id:"306"
```
Woher die ID 306 kommt verstehe ich auch nicht. Der Wettbewert hat die ID 102. Oder welche ID wird da genommen?

**Comment by digedag** [comment]
Der Redirect ist korrekt. Die ID kommt vom gewählten SysFolder. Übergabe des Wettbewerbs ist nicht notwendig, weil der Wert serverseitig gespeichert wird. Da du keine Fehlermeldung erhälst, passt das schon alles. Der Cache-Clear wird [an dieser Stelle](https://github.com/digedag/cfc_league/blob/a6fca5ebfa86194f5a4ad7c1632800a6e1fe5a08/mod1/class.tx_cfcleague_selector.php#L107) angetriggert. Da musst du mal debuggen, was da bei dir passiert...

**Comment by digedag** [comment]
Das Problem sollte diese Ursache haben: digedag/rn_base#95

**Comment by digedag** [comment]
Bitte mal rn_base und cfc_league aktualisieren. Dann sollte es hoffentlich funktionieren. War wohl doch ein Bug!

**Comment by stemeda** [comment]
Tabelle wird gefüllt! Danke :-)
